name: Update Monorepo Submodule Pointer


on:
  push:
    branches:
      - main
      - dev


jobs:
  update-monorepo:
    uses: ChaosCantrip/DestinyTCG/.github/workflows/update-monorepo.yml@main
    with:
      submodule-reference: polling-service
      branch: ${{ github.ref_name }}
      commit-sha: ${{ github.sha }}
    secrets:
      monorepo-read-pat: ${{ secrets.MONOREPO_READ_PAT }}
      monorepo-write-pat: ${{ secrets.MONOREPO_WRITE_PAT }}
